### ISSUE TITLE
Multi-key update

### ISSUE THREAD

**Issue by egiltane** [unioslo/pysquril#14]
# Updates

I’m wondering whether updates performed via `set=` might support multiple top-level properties, such as `set=foo,bar`, allowing for multiple key/value pairs in the payload:

```json
{"foo": 1, "bar": 2}
```

which updates both `foo` and `bar` simultaneously. Updates can be performed sequentially, of course, but doing so will result in multiple entries in the audit log.

# Error/status reporting

Attempting to update multiple keys simultaneously results in the upstream API to return `500 Internal Server Error`, with

```json
{"message": "Internal Server Error"}
```

as payload. The logs of the upstream API indicate “Cannot update more than one key per statement”, presumably due to an [assertion](https://github.com/unioslo/pysquril/blob/c4b9388f6285ffee0bc7ddd74d36081e7699c65f/pysquril/generator.py#L386) failing. Details are not exposed by the API. Ideally, a response code of 400 would indicate erroneous input, accompanied by a respective status field in the payload returned to the client.

Positive feedback upon successfully updating records is currently signalled via the following payload:

```json
{"data": "data updated"}
```

Ideally, the key used to indicate change would be consistent across methods (PUT, PATCH, DELETE), i. e. always use `message` (or a different key, such as `status`, for that matter).

**Comment by leondutoit** [comment]
Thanks for the feature request, can you move the "Error/status reporting" to an issue on https://github.com/unioslo/tsd-file-api/issues ? It is a bit intertwined with error handling in this library but it is more appropriate there since that is where the HTTP interface is implemented :)

**Comment by egiltane** [comment]
Sure!

[Done](https://github.com/unioslo/tsd-file-api/issues/133).

**Comment by leondutoit** [comment]
Fixed in https://github.com/unioslo/pysquril/pull/15
