### ISSUE TITLE
Add audit on data delete

### ISSUE THREAD

**Issue by kouylekov-usit** [unioslo/pysquril#3]

**Comment by leondutoit** [comment]
What to add though?

**Comment by f-krull** [comment]
To clarify, with "on data delete" this issue refers to a submission (not the whole table)

**Comment by kouylekov-usit** [comment]
I would say the entire line ...

**Comment by leondutoit** [comment]
So if all rows are deleted, you want the audit to contain a copy of all data? Like said, the audit is intended to keep track of changes to existing data, not to allow people to rollback deletions.

**Comment by f-krull** [comment]
If a single row is deleted, we maybe want to have it part of the audit log? Currently its not

**Comment by leondutoit** [comment]
What is the use case? My reasoning for not including deleted data in the audit log was:
* deletion should be deletion
* would end up storing too much data
* the use case I had in mind was: being able to display the history of edited data that has not been deleted

One could argue that "audit log" is the wrong term for what I implemented. I still think we should let deleted data be deleted. Which actually brings up another thing that has to be implemented: the deletion of any audit entries when data is deleted...

**Comment by f-krull** [comment]
I'm fine with the current behavior. 
One could argue that delete is a form of editing (very similar to setting all values of a submission to null). With research centers that use Nettskjemas for data collection and employ multiple people curating the responses, it's not unthinkable that they want to keep track of any deletions as well.

**Comment by leondutoit** [comment]
It is not unthinkable no, but I'd rather tell them that delete means delete.

**Comment by leondutoit** [comment]
Alright, closing this then.

**Comment by leondutoit** [comment]
For the record, this was implemented: deleted data is recorded in the audit.
