### ISSUE TITLE
Altering properties of tables

### ISSUE THREAD

**Issue by egiltane** [unioslo/pysquril#43]
It would be convienient to be able to alter the properties of an existing table. The most obvious use case that comes to mind is to change the name of an existing table, much like one would change the name of a file or directory. However, there might be other parameters one may want to change during the life cycle of a table.

One way to implement such functionality could be by means of a generic request that leaves room for future extensions by extending the grammar. Such as

```
POST .../tables/foo
```

```json
{
    "action": "rename",
    "name": "bar"
}
```

**Comment by leondutoit** [comment]
Another property that could be useful to alter is to add an index on a selected key

**Comment by leondutoit** [comment]
Resolved within the scope of table names.
