### ISSUE TITLE
Handling quotes inside JSON fields

### ISSUE THREAD

**Issue by leondutoit** [unioslo/pysquril#45]
```
tsd-file-api[3121883]: [E 240119 12:03:43 api:2562] Internal Server Error. syntax error at or near "gamle"
tsd-file-api[3121883]:     LINE 1: ...arna i det hele tatt - av hensyn til oss som var 'gamle og i...
tsd-file-api[3121883]: [E 240119 12:03:43 web:2344] 500 PATCH /v1/p23/survey/268938/submissions?set=answers&where=metadata.submission_id=eq.28948773 (127.0.0.1) 6.50ms
```

**Comment by leondutoit** [comment]
@drmowinckels ^

**Comment by f-krull** [comment]
@drmowinckels
This is also the reason for the failed bevex uploads on Friday. 

Replacing all single quotes with escaped double quotes would be a workaround.
![Selection_491](https://github.com/unioslo/pysquril/assets/11461352/6c4ce34b-1307-4779-b0ad-a4ced7cb44b6)


[bevex upload src](https://github.uio.no/IT-WEBAPPS/bevex/blob/main/src/logic/tsdbasic/tsdApi.ts#L74-L90)

**Comment by drmowinckels** [comment]
Alright. Thanks! I'll have s look at how to do this.

**Comment by f-krull** [comment]
> Alright. Thanks! I'll have s look at how to do this.

```js
        const r = await fetch("./save", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            body: JSON.stringify(jsPsych.data.get().json()).replaceAll("'", "\\\\\\\"")
        });
```

**Comment by f-krull** [comment]
> thats a lot of escaping! :D

I know. I stopped counting. It's like Inception

**Comment by leondutoit** [comment]
Fix is merged but not deployed yet. Will update when it is.
